(ns doubletake.lang.basic.core
  (:use doubletake.lang.basic.parser
        [doubletake.parser.util :as util]))

(defn _processor [ast]
  ; takes an AST as generated by the lexer and parser, then processes it to
  ; def and use pairs.
)

(defn parse [file]
  (util/parser Lines (re-all-matches util/splitter (slurp file))))

(defn process [file]
  (_processor (parse file)))
