(ns doubletake.lang.basic.core
  (:use clojure.set 
        doubletake.lang.basic.parser
        [doubletake.parser.util :as util]))

(defn _processor [ast]
  ; takes an AST as generated by the lexer and parser, then processes it to
  ; def and use pairs.
)

(defn parse [input]
  (cond
    (string? input)
      (util/parser Lines 
                   (util/prep (util/re-all-matches util/splitter 
                                                   input)))
    true
      (util/parser Lines 
                   (util/prep (util/re-all-matches util/splitter 
                                                   (slurp input))))))


(defn process [file]
  (_processor (parse file)))
