; Okay... here goes the test file!
FloatingPointType:
    float
    double

; Got the FloatingPointType OK...

IntegralType:
    byte
    short
    int
    long
    char

; Got the IntegralType OK...

NumericType:
    IntegralType
    FloatingPointType

Identifier:
    #"[a-zA-Z][a-zA-Z0-9_$]*"

TypeName:
    Identifier
    TypeName . Identifier

; And the NeumericType! All on the grammar tree now...

AnyType:
    NumericType
    TypeName

